In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

performing univariate analysis

In [3]:
df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

Handle the missing values

In [4]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

Check for Categorical columns and perform encoding.

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
df['Surname'] = le.fit_transform(df['Surname'])
df['Geography'] = le.fit_transform(df['Geography'])
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,1999,771,0,1,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,1336,516,0,1,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,1570,709,0,0,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,2345,772,1,1,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,2751,792,0,0,28,4,130142.79,1,1,0,38190.78,0

Split the data into dependent and independent variables

In [6]:
x = df.drop(['Gender', 'Surname', 'Geography', 'EstimatedSalary'],axis=1)
y = df[['EstimatedSalary']].values

In [7]:
x

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited
0,1,15634602,619,42,2,0.00,1,1,1,1
1,2,15647311,608,41,1,83807.86,1,0,1,0
2,3,15619304,502,42,8,159660.80,3,1,0,1
3,4,15701354,699,39,1,0.00,2,0,0,0
4,5,15737888,850,43,2,125510.82,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,0
9997,9998,15584532,709,36,7,0.00,1,0,1,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,0

In [8]:
y

array([[101348.88],
       [112542.58],
       [113931.57],
       ...,
       [ 42085.58],
       [ 92888.52],
       [ 38190.78]])

scale the independent variables

In [9]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()


scaledX = scale.fit_transform(x,y)

print(scaledX)

[[-1.73187761 -0.78321342 -0.32622142 ...  0.64609167  0.97024255
   1.97716468]
 [-1.7315312  -0.60653412 -0.44003595 ... -1.54776799  0.97024255
  -0.50577476]
 [-1.73118479 -0.99588476 -1.53679418 ...  0.64609167 -1.03067011
   1.97716468]
 ...
 [ 1.73118479 -1.47928179  0.60498839 ... -1.54776799  0.97024255
   1.97716468]
 [ 1.7315312  -0.11935577  1.25683526 ...  0.64609167 -1.03067011
   1.97716468]
 [ 1.73187761 -0.87055909  1.46377078 ...  0.64609167 -1.03067011
  -0.50577476]]

Split the data into training and testing

In [10]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.3,random_state=0)

In [11]:
ytest

array([[192852.67],
       [128702.1 ],
       [ 75732.25],
       ...,
       [167400.29],
       [ 70849.47],
       [ 33759.41]])

In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
regressor = Sequential()
regressor.add(Dense(4, activation='relu')) # Input
regressor.add(Dense(12, activation='relu')) # 1st hid. layer
regressor.add(Dense(8, activation='relu')) # 2nd hid. layer
regressor.add(Dense(9, activation='relu')) # 3rd hid. layer
regressor.add(Dense(1,activation='linear')) # output layer

In [14]:
regressor.compile(optimizer='adam',loss='mse',metrics=['mse'])

In [15]:
regressor.fit(xtrain,ytrain,batch_size=10,epochs=300)

Epoch 1/300
700/700 [==============================] - 1s 1ms/step - loss: 14768052224.0000 - mse: 14768052224.0000
Epoch 2/300
700/700 [==============================] - 1s 1ms/step - loss: 3325200384.0000 - mse: 3325200128.0000
Epoch 3/300
700/700 [==============================] - 1s 1ms/step - loss: 3328278272.0000 - mse: 3328278272.0000
Epoch 4/300
700/700 [==============================] - 1s 1ms/step - loss: 3344280576.0000 - mse: 3344280576.0000
Epoch 5/300
700/700 [==============================] - 1s 1ms/step - loss: 3341584640.0000 - mse: 3341584640.0000
Epoch 6/300
700/700 [==============================] - 1s 1ms/step - loss: 3341181440.0000 - mse: 3341181440.0000
Epoch 7/300
700/700 [==============================] - 1s 1ms/step - loss: 3339412224.0000 - mse: 3339412224.0000
Epoch 8/300
700/700 [==============================] - 1s 1ms/step - loss: 3344678400.0000 - mse: 3344678400.0000
Epoch 9/300
700/700 [==============================] - 1s 1ms/step - loss: 3338733568.0000 - mse: 3338733568.0000
Epoch 10/300
700/700 [==============================] - 1s 1ms/step - loss: 3353687296.0000 - mse: 3353687296.0000
Epoch 11/300
700/700 [==============================] - 1s 1ms/step - loss: 3345235200.0000 - mse: 3345235200.0000
Epoch 12/300
700/700 [==============================] - 1s 1ms/step - loss: 3333363968.0000 - mse: 3333363968.0000
Epoch 13/300
700/700 [==============================] - 1s 1ms/step - loss: 3348696576.0000 - mse: 3348696576.0000
Epoch 14/300
700/700 [==============================] - 1s 1ms/step - loss: 3334076928.0000 - mse: 3334076928.0000
Epoch 15/300
700/700 [==============================] - 1s 1ms/step - loss: 3344874752.0000 - mse: 3344874752.0000
Epoch 16/300
700/700 [==============================] - 1s 1ms/step - loss: 3344657664.0000 - mse: 3344657664.0000
Epoch 17/300
700/700 [==============================] - 1s 1ms/step - loss: 3345768960.0000 - mse: 3345768960.0000
Epoch 18/300
700/700 [==============================] - 1s 1ms/step - loss: 3338540800.0000 - mse: 3338540800.0000
Epoch 19/300
700/700 [==============================] - 1s 1ms/step - loss: 3336170496.0000 - mse: 3336170496.0000
Epoch 20/300
700/700 [==============================] - 1s 1ms/step - loss: 3339175168.0000 - mse: 3339175168.0000
Epoch 21/300
700/700 [==============================] - 1s 1ms/step - loss: 3336282112.0000 - mse: 3336282112.0000
Epoch 22/300
700/700 [==============================] - 1s 1ms/step - loss: 3350525696.0000 - mse: 3350525696.0000
Epoch 23/300
700/700 [==============================] - 1s 1ms/step - loss: 3348089344.0000 - mse: 3348089344.0000
Epoch 24/300
700/700 [==============================] - 1s 1ms/step - loss: 3341026816.0000 - mse: 3341026816.0000
Epoch 25/300
700/700 [==============================] - 1s 1ms/step - loss: 3340167936.0000 - mse: 3340167936.0000
Epoch 26/300
700/700 [==============================] - 1s 1ms/step - loss: 3346858240.0000 - mse: 3346858240.0000
Epoch 27/300
700/700 [==============================] - 1s 983us/step - loss: 3338142720.0000 - mse: 3338142720.0000
Epoch 28/300
700/700 [==============================] - 1s 1ms/step - loss: 3341869312.0000 - mse: 3341869312.0000
Epoch 29/300
700/700 [==============================] - 1s 1ms/step - loss: 3352188928.0000 - mse: 3352189440.0000
Epoch 30/300
700/700 [==============================] - 1s 1ms/step - loss: 3339408384.0000 - mse: 3339408384.0000
Epoch 31/300
700/700 [==============================] - 1s 1ms/step - loss: 3335894272.0000 - mse: 3335894272.0000
Epoch 32/300
700/700 [==============================] - 1s 1ms/step - loss: 3339504896.0000 - mse: 3339504896.0000
Epoch 33/300
700/700 [==============================] - 1s 1ms/step - loss: 3340337664.0000 - mse: 3340337664.0000
Epoch 34/300
700/700 [==============================] - 1s 1ms/step - loss: 3334922752.0000 - mse: 3334922752.0000
Epoch 35/300
700/700 [==============================] - 1s 1ms/step - loss: 3338176768.0000 - mse: 3338176768.0000
Epoch 36/300
700/700 [==============================] - 1s 1ms/step - loss: 3337505280.0000 - mse: 3337505280.0000
Epoch 37/300
700/700 [==============================] - 1s 1ms/step - loss: 3337311232.0000 - mse: 3337311232.0000
Epoch 38/300
700/700 [==============================] - 1s 1ms/step - loss: 3328749824.0000 - mse: 3328749824.0000
Epoch 39/300
700/700 [==============================] - 1s 1ms/step - loss: 3339635200.0000 - mse: 3339635200.0000
Epoch 40/300
700/700 [==============================] - 1s 1ms/step - loss: 3334775040.0000 - mse: 3334775040.0000
Epoch 41/300
700/700 [==============================] - 1s 1ms/step - loss: 3338396416.0000 - mse: 3338396416.0000
Epoch 42/300
700/700 [==============================] - 1s 1ms/step - loss: 3337740544.0000 - mse: 3337740544.0000
Epoch 43/300
700/700 [==============================] - 1s 1ms/step - loss: 3334098432.0000 - mse: 3334098432.0000
Epoch 44/300
700/700 [==============================] - 1s 1ms/step - loss: 3343970048.0000 - mse: 3343970048.0000
Epoch 45/300
700/700 [==============================] - 1s 1ms/step - loss: 3335197952.0000 - mse: 3335197952.0000
Epoch 46/300
700/700 [==============================] - 1s 1ms/step - loss: 3335469824.0000 - mse: 3335469824.0000
Epoch 47/300
700/700 [==============================] - 1s 1ms/step - loss: 3335635200.0000 - mse: 3335635712.0000
Epoch 48/300
700/700 [==============================] - 1s 1ms/step - loss: 3342833664.0000 - mse: 3342833664.0000
Epoch 49/300
700/700 [==============================] - 1s 1ms/step - loss: 3344411648.0000 - mse: 3344411648.0000
Epoch 50/300
700/700 [==============================] - 1s 1ms/step - loss: 3338506240.0000 - mse: 3338506240.0000
Epoch 51/300
700/700 [==============================] - 1s 1ms/step - loss: 3330553344.0000 - mse: 3330553344.0000
Epoch 52/300
700/700 [==============================] - 1s 1ms/step - loss: 3335999232.0000 - mse: 3335999232.0000
Epoch 53/300
700/700 [==============================] - 1s 1ms/step - loss: 3336403200.0000 - mse: 3336403200.0000
Epoch 54/300
700/700 [==============================] - 1s 1ms/step - loss: 3342123264.0000 - mse: 3342123264.0000
Epoch 55/300
700/700 [==============================] - 1s 1ms/step - loss: 3331484672.0000 - mse: 3331484672.0000
Epoch 56/300
700/700 [==============================] - 1s 1ms/step - loss: 3339558144.0000 - mse: 3339558144.0000
Epoch 57/300
700/700 [==============================] - 1s 1ms/step - loss: 3335151872.0000 - mse: 3335151872.0000
Epoch 58/300
700/700 [==============================] - 1s 1ms/step - loss: 3341764608.0000 - mse: 3341764352.0000
Epoch 59/300
700/700 [==============================] - 1s 1ms/step - loss: 3331816192.0000 - mse: 3331816192.0000
Epoch 60/300
700/700 [==============================] - 1s 1ms/step - loss: 3333405952.0000 - mse: 3333405952.0000
Epoch 61/300
700/700 [==============================] - 1s 991us/step - loss: 3333352960.0000 - mse: 3333352960.0000
Epoch 62/300
700/700 [==============================] - 1s 1ms/step - loss: 3333239552.0000 - mse: 3333239552.0000
Epoch 63/300
700/700 [==============================] - 1s 1ms/step - loss: 3334686976.0000 - mse: 3334686976.0000
Epoch 64/300
700/700 [==============================] - 1s 1ms/step - loss: 3339654912.0000 - mse: 3339654912.0000
Epoch 65/300
700/700 [==============================] - 1s 1ms/step - loss: 3329216256.0000 - mse: 3329216256.0000
Epoch 66/300
700/700 [==============================] - 1s 1ms/step - loss: 3331842560.0000 - mse: 3331842560.0000
Epoch 67/300
700/700 [==============================] - 1s 1ms/step - loss: 3333384960.0000 - mse: 3333384960.0000
Epoch 68/300
700/700 [==============================] - 1s 1ms/step - loss: 3339846656.0000 - mse: 3339846656.0000
Epoch 69/300
700/700 [==============================] - 1s 1ms/step - loss: 3335385088.0000 - mse: 3335385088.0000
Epoch 70/300
700/700 [==============================] - 1s 1ms/step - loss: 3332128000.0000 - mse: 3332128000.0000
Epoch 71/300
700/700 [==============================] - 1s 984us/step - loss: 3336573696.0000 - mse: 3336573696.0000
Epoch 72/300
700/700 [==============================] - 1s 997us/step - loss: 3337452288.0000 - mse: 3337452288.0000
Epoch 73/300
700/700 [==============================] - 1s 1ms/step - loss: 3337241344.0000 - mse: 3337242112.0000
Epoch 74/300
700/700 [==============================] - 1s 1ms/step - loss: 3333148160.0000 - mse: 3333148160.0000
Epoch 75/300
700/700 [==============================] - 1s 1ms/step - loss: 3338326272.0000 - mse: 3338326272.0000
Epoch 76/300
700/700 [==============================] - 1s 993us/step - loss: 3332490496.0000 - mse: 3332490496.0000
Epoch 77/300
700/700 [==============================] - 1s 1ms/step - loss: 3328535552.0000 - mse: 3328535552.0000
Epoch 78/300
700/700 [==============================] - 1s 1ms/step - loss: 3325728256.0000 - mse: 3325728256.0000
Epoch 79/300
700/700 [==============================] - 1s 1ms/step - loss: 3337263872.0000 - mse: 3337263872.0000
Epoch 80/300
700/700 [==============================] - 1s 1ms/step - loss: 3341435904.0000 - mse: 3341435904.0000
Epoch 81/300
700/700 [==============================] - 1s 1ms/step - loss: 3336728320.0000 - mse: 3336728320.0000
Epoch 82/300
700/700 [==============================] - 1s 984us/step - loss: 3337377536.0000 - mse: 3337377536.0000
Epoch 83/300
700/700 [==============================] - 1s 993us/step - loss: 3340896512.0000 - mse: 3340896512.0000
Epoch 84/300
700/700 [==============================] - 1s 987us/step - loss: 3337161216.0000 - mse: 3337161216.0000
Epoch 85/300
700/700 [==============================] - 1s 1ms/step - loss: 3347958528.0000 - mse: 3347958528.0000
Epoch 86/300
700/700 [==============================] - 1s 1ms/step - loss: 3341239296.0000 - mse: 3341238528.0000
Epoch 87/300
700/700 [==============================] - 1s 1ms/step - loss: 3340020480.0000 - mse: 3340020480.0000
Epoch 88/300
700/700 [==============================] - 1s 1ms/step - loss: 3342496256.0000 - mse: 3342496256.0000
Epoch 89/300
700/700 [==============================] - 1s 1ms/step - loss: 3334993920.0000 - mse: 3334993920.0000
Epoch 90/300
700/700 [==============================] - 1s 1ms/step - loss: 3340994048.0000 - mse: 3340994048.0000
Epoch 91/300
700/700 [==============================] - 1s 1ms/step - loss: 3332175104.0000 - mse: 3332175104.0000
Epoch 92/300
700/700 [==============================] - 1s 970us/step - loss: 3326850816.0000 - mse: 3326850816.0000
Epoch 93/300
700/700 [==============================] - 1s 1ms/step - loss: 3330096128.0000 - mse: 3330096128.0000
Epoch 94/300
700/700 [==============================] - 1s 1ms/step - loss: 3339707392.0000 - mse: 3339707392.0000
Epoch 95/300
700/700 [==============================] - 1s 1ms/step - loss: 3336735232.0000 - mse: 3336735232.0000
Epoch 96/300
700/700 [==============================] - 1s 1ms/step - loss: 3330524160.0000 - mse: 3330524160.0000
Epoch 97/300
700/700 [==============================] - 1s 1ms/step - loss: 3330077952.0000 - mse: 3330077952.0000
Epoch 98/300
700/700 [==============================] - 1s 1ms/step - loss: 3336179456.0000 - mse: 3336179456.0000
Epoch 99/300
700/700 [==============================] - 1s 1ms/step - loss: 3330832128.0000 - mse: 3330832640.0000
Epoch 100/300
700/700 [==============================] - 1s 1ms/step - loss: 3330455552.0000 - mse: 3330455552.0000
Epoch 101/300
700/700 [==============================] - 1s 1ms/step - loss: 3332000000.0000 - mse: 3332000000.0000
Epoch 102/300
700/700 [==============================] - 1s 1ms/step - loss: 3329752832.0000 - mse: 3329752832.0000
Epoch 103/300
700/700 [==============================] - 1s 1ms/step - loss: 3329181696.0000 - mse: 3329181696.0000
Epoch 104/300
700/700 [==============================] - 1s 1ms/step - loss: 3330797568.0000 - mse: 3330797568.0000
Epoch 105/300
700/700 [==============================] - 1s 1ms/step - loss: 3324078080.0000 - mse: 3324078080.0000
Epoch 106/300
700/700 [==============================] - 1s 1ms/step - loss: 3329663488.0000 - mse: 3329663488.0000
Epoch 107/300
700/700 [==============================] - 1s 1ms/step - loss: 3331407360.0000 - mse: 3331408128.0000
Epoch 108/300
700/700 [==============================] - 1s 1ms/step - loss: 3335330816.0000 - mse: 3335330816.0000
Epoch 109/300
700/700 [==============================] - 1s 1ms/step - loss: 3337947648.0000 - mse: 3337947648.0000
Epoch 110/300
700/700 [==============================] - 1s 1ms/step - loss: 3328872192.0000 - mse: 3328872192.0000
Epoch 111/300
700/700 [==============================] - 1s 1ms/step - loss: 3331028992.0000 - mse: 3331028992.0000
Epoch 112/300
700/700 [==============================] - 1s 1ms/step - loss: 3330307840.0000 - mse: 3330307840.0000
Epoch 113/300
700/700 [==============================] - 1s 1ms/step - loss: 3335482624.0000 - mse: 3335482624.0000
Epoch 114/300
700/700 [==============================] - 1s 1ms/step - loss: 3329322752.0000 - mse: 3329323264.0000
Epoch 115/300
700/700 [==============================] - 1s 1ms/step - loss: 3332302080.0000 - mse: 3332302080.0000
Epoch 116/300
700/700 [==============================] - 1s 1ms/step - loss: 3332098560.0000 - mse: 3332098560.0000
Epoch 117/300
700/700 [==============================] - 1s 1ms/step - loss: 3346860800.0000 - mse: 3346860800.0000
Epoch 118/300
700/700 [==============================] - 1s 1ms/step - loss: 3341231872.0000 - mse: 3341231872.0000
Epoch 119/300
700/700 [==============================] - 1s 1ms/step - loss: 3335729152.0000 - mse: 3335729152.0000
Epoch 120/300
700/700 [==============================] - 1s 1ms/step - loss: 3339204352.0000 - mse: 3339204352.0000
Epoch 121/300
700/700 [==============================] - 1s 1ms/step - loss: 3331669504.0000 - mse: 3331669504.0000
Epoch 122/300
700/700 [==============================] - 1s 1ms/step - loss: 3329976832.0000 - mse: 3329976832.0000
Epoch 123/300
700/700 [==============================] - 1s 1ms/step - loss: 3336082688.0000 - mse: 3336082688.0000
Epoch 124/300
700/700 [==============================] - 1s 1ms/step - loss: 3329436416.0000 - mse: 3329436416.0000
Epoch 125/300
700/700 [==============================] - 1s 1ms/step - loss: 3328499712.0000 - mse: 3328499712.0000
Epoch 126/300
700/700 [==============================] - 1s 1ms/step - loss: 3333614592.0000 - mse: 3333614336.0000
Epoch 127/300
700/700 [==============================] - 1s 1ms/step - loss: 3332697856.0000 - mse: 3332697856.0000
Epoch 128/300
700/700 [==============================] - 1s 1ms/step - loss: 3329760256.0000 - mse: 3329760256.0000
Epoch 129/300
700/700 [==============================] - 1s 1ms/step - loss: 3330653696.0000 - mse: 3330653696.0000
Epoch 130/300
700/700 [==============================] - 1s 1ms/step - loss: 3337638400.0000 - mse: 3337638400.0000
Epoch 131/300
700/700 [==============================] - 1s 1ms/step - loss: 3330140416.0000 - mse: 3330140416.0000
Epoch 132/300
700/700 [==============================] - 1s 998us/step - loss: 3336736256.0000 - mse: 3336736256.0000
Epoch 133/300
700/700 [==============================] - 1s 1ms/step - loss: 3332050432.0000 - mse: 3332050432.0000
Epoch 134/300
700/700 [==============================] - 1s 1ms/step - loss: 3334352640.0000 - mse: 3334352640.0000
Epoch 135/300
700/700 [==============================] - 1s 1ms/step - loss: 3331678208.0000 - mse: 3331678208.0000
Epoch 136/300
700/700 [==============================] - 1s 1ms/step - loss: 3330505728.0000 - mse: 3330505728.0000
Epoch 137/300
700/700 [==============================] - 1s 1ms/step - loss: 3332419072.0000 - mse: 3332419072.0000
Epoch 138/300
700/700 [==============================] - 1s 1ms/step - loss: 3333469952.0000 - mse: 3333469952.0000
Epoch 139/300
700/700 [==============================] - 1s 1ms/step - loss: 3336001024.0000 - mse: 3336001024.0000
Epoch 140/300
700/700 [==============================] - 1s 1ms/step - loss: 3327027456.0000 - mse: 3327027456.0000
Epoch 141/300
700/700 [==============================] - 1s 1ms/step - loss: 3332574720.0000 - mse: 3332574720.0000
Epoch 142/300
700/700 [==============================] - 1s 1ms/step - loss: 3332817664.0000 - mse: 3332817664.0000
Epoch 143/300
700/700 [==============================] - 1s 1ms/step - loss: 3335176960.0000 - mse: 3335176704.0000
Epoch 144/300
700/700 [==============================] - 1s 1ms/step - loss: 3332155648.0000 - mse: 3332155648.0000
Epoch 145/300
700/700 [==============================] - 1s 1ms/step - loss: 3333864448.0000 - mse: 3333863680.0000
Epoch 146/300
700/700 [==============================] - 1s 1ms/step - loss: 3333033216.0000 - mse: 3333033216.0000
Epoch 147/300
700/700 [==============================] - 1s 1ms/step - loss: 3332881408.0000 - mse: 3332881408.0000
Epoch 148/300
700/700 [==============================] - 1s 1ms/step - loss: 3334417152.0000 - mse: 3334417152.0000
Epoch 149/300
700/700 [==============================] - 1s 1ms/step - loss: 3323152384.0000 - mse: 3323152384.0000
Epoch 150/300
700/700 [==============================] - 1s 1ms/step - loss: 3327994368.0000 - mse: 3327994368.0000
Epoch 151/300
700/700 [==============================] - 1s 1ms/step - loss: 3333767680.0000 - mse: 3333767424.0000
Epoch 152/300
700/700 [==============================] - 1s 1ms/step - loss: 3332498176.0000 - mse: 3332498176.0000
Epoch 153/300
700/700 [==============================] - 1s 1ms/step - loss: 3336545280.0000 - mse: 3336545280.0000
Epoch 154/300
700/700 [==============================] - 1s 1ms/step - loss: 3330292992.0000 - mse: 3330292992.0000
Epoch 155/300
700/700 [==============================] - 1s 1ms/step - loss: 3330454016.0000 - mse: 3330454016.0000
Epoch 156/300
700/700 [==============================] - 1s 1ms/step - loss: 3330783744.0000 - mse: 3330783744.0000
Epoch 157/300
700/700 [==============================] - 1s 984us/step - loss: 3344363008.0000 - mse: 3344363008.0000
Epoch 158/300
700/700 [==============================] - 1s 1ms/step - loss: 3342881536.0000 - mse: 3342881536.0000
Epoch 159/300
700/700 [==============================] - 1s 998us/step - loss: 3335436288.0000 - mse: 3335436288.0000
Epoch 160/300
700/700 [==============================] - 1s 1ms/step - loss: 3332065536.0000 - mse: 3332065536.0000
Epoch 161/300
700/700 [==============================] - 1s 1ms/step - loss: 3330582016.0000 - mse: 3330582016.0000
Epoch 162/300
700/700 [==============================] - 1s 1ms/step - loss: 3332251904.0000 - mse: 3332251904.0000
Epoch 163/300
700/700 [==============================] - 1s 1ms/step - loss: 3332049408.0000 - mse: 3332049408.0000
Epoch 164/300
700/700 [==============================] - 1s 1ms/step - loss: 3339801856.0000 - mse: 3339801856.0000
Epoch 165/300
700/700 [==============================] - 1s 1ms/step - loss: 3322011392.0000 - mse: 3322011392.0000
Epoch 166/300
700/700 [==============================] - 1s 1ms/step - loss: 3328254208.0000 - mse: 3328254464.0000
Epoch 167/300
700/700 [==============================] - 1s 1ms/step - loss: 3334890240.0000 - mse: 3334890240.0000
Epoch 168/300
700/700 [==============================] - 1s 1ms/step - loss: 3331295744.0000 - mse: 3331295744.0000
Epoch 169/300
700/700 [==============================] - 1s 1ms/step - loss: 3330347776.0000 - mse: 3330347776.0000
Epoch 170/300
700/700 [==============================] - 1s 1ms/step - loss: 3329676288.0000 - mse: 3329676288.0000
Epoch 171/300
700/700 [==============================] - 1s 1ms/step - loss: 3328728064.0000 - mse: 3328728064.0000
Epoch 172/300
700/700 [==============================] - 1s 1ms/step - loss: 3330369280.0000 - mse: 3330369280.0000
Epoch 173/300
700/700 [==============================] - 1s 1ms/step - loss: 3329991168.0000 - mse: 3329991168.0000
Epoch 174/300

In [16]:
ypred = regressor.predict(xtest)

In [17]:
ypred

array([[98892.17],
       [99548.85],
       [99324.61],
       ...,
       [99356.44],
       [98862.67],
       [98894.37]], dtype=float32)

In [18]:
ytest

array([[192852.67],
       [128702.1 ],
       [ 75732.25],
       ...,
       [167400.29],
       [ 70849.47],
       [ 33759.41]])

In [19]:
pd.DataFrame({'Actual values':ytest.flatten(),
              'Predicted values':ypred.flatten()})

      Actual values  Predicted values
0         192852.67      98892.171875
1         128702.10      99548.851562
2          75732.25      99324.609375
3          89368.59      99871.500000
4         135662.17     100260.117188
...             ...               ...
2995      147606.71      99774.617188
2996       55829.25      99073.242188
2997      167400.29      99356.437500
2998       70849.47      98862.671875
2999       33759.41      98894.367188

[3000 rows x 2 columns]